import 'package:flutter/material.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  Widget _section(String title, String body) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 22),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(fontSize: 19, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 8),
          Text(
            body,
            style: const TextStyle(
              fontSize: 15,
              height: 1.5,
              color: Colors.black87,
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('CARDIOGUARD')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(22),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _section(
              'Data Collection',
              'CardioGuard collects account information and health assessment inputs only for the purpose of providing heart disease risk predictions.',
            ),
            _section(
              'Health Information',
              'Health-related information entered into the app is used to generate prediction results and support user monitoring. The app does not replace professional medical advice.',
            ),
            _section(
              'Data Storage',
              'User profiles and prediction history may be stored securely using Firebase services. Access is restricted based on authenticated user accounts.',
            ),
            _section(
              'Data Usage',
              'Collected data is used only for prediction, history tracking, and practitioner review features within the system.',
            ),
            _section(
              'Medical Disclaimer',
              'Prediction results are generated by a machine learning model and should be treated as decision-support information, not a medical diagnosis.',
            ),
          ],
        ),
      ),
    );
  }
}
