// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHJ7dEiSpn9OTkf8gDPXKrbHxgbL5cIi8',
    appId: '1:255048596022:web:68f462b667677a29b43697',
    messagingSenderId: '255048596022',
    projectId: 'heartdiseasepredictionfyp',
    authDomain: 'heartdiseasepredictionfyp.firebaseapp.com',
    storageBucket: 'heartdiseasepredictionfyp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIVODCHwGh_btt3KlL8k107ll3QnpOP-k',
    appId: '1:255048596022:android:32227002af53106fb43697',
    messagingSenderId: '255048596022',
    projectId: 'heartdiseasepredictionfyp',
    storageBucket: 'heartdiseasepredictionfyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiW_60R8Yt0QVLZOx1P8EIT3gxxE72lFo',
    appId: '1:255048596022:ios:7f21e5cfb4f1fadcb43697',
    messagingSenderId: '255048596022',
    projectId: 'heartdiseasepredictionfyp',
    storageBucket: 'heartdiseasepredictionfyp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiW_60R8Yt0QVLZOx1P8EIT3gxxE72lFo',
    appId: '1:255048596022:ios:7f21e5cfb4f1fadcb43697',
    messagingSenderId: '255048596022',
    projectId: 'heartdiseasepredictionfyp',
    storageBucket: 'heartdiseasepredictionfyp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHJ7dEiSpn9OTkf8gDPXKrbHxgbL5cIi8',
    appId: '1:255048596022:web:42c284e405d64eccb43697',
    messagingSenderId: '255048596022',
    projectId: 'heartdiseasepredictionfyp',
    authDomain: 'heartdiseasepredictionfyp.firebaseapp.com',
    storageBucket: 'heartdiseasepredictionfyp.firebasestorage.app',
  );
}
